# Generated by Django 4.0.3 on 2022-04-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('deptid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('empid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('deptid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
    ]
